"""Create horarios table

Revision ID: 29357d948948
Revises: f44d861543a8
Create Date: 2025-10-27 18:15:52.862878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29357d948948'
down_revision = 'f44d861543a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=100), nullable=False),
    sa.Column('docente', sa.String(length=120), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('salon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios')
    # ### end Alembic commands ###
